TASK 05_ Pivot Tables + Stack/Unstack

Đọc file đã merge:

In [1]:
import pandas as pd

full_data = pd.read_csv("../data_clean/full_merged_data.csv")

5.1 - Tạo bảng pivot thể hiện thời gian sửa chữa trung bình theo facility_type × building.

In [2]:
pivot_repair_time = pd.pivot_table(
    full_data,
    values="duration_hours",
    index="facility_type",
    columns="building",
    aggfunc="mean"
)

pivot_repair_time

building          A   A-BLOCK       B   BLOCK C         C   TOA A
facility_type
Hoi Truong     3.00       NaN  1.5000  3.916667  5.000000  3.6875
Lab             NaN  3.089286  3.1875       NaN       NaN  3.1250
Phong  Hoc     2.00  2.000000     NaN  2.125000       NaN     NaN
Phong Hoc       NaN  2.875000  2.3500       NaN  4.250000  3.8500
Studio         4.25  3.250000  3.5000  2.875000  2.416667     NaN

5.2 - Tạo bảng pivot về số lượng sự cố theo building × severity.

In [3]:
pivot_incident_count = pd.pivot_table(
    full_data,
    values="report_id",
    index="building",
    columns="severity",
    aggfunc="count",
    fill_value=0
)

pivot_incident_count

severity  high  low  medium
building
A            4    8       3
A-BLOCK     15   13       8
B           11    8      10
BLOCK C      6    8      12
C            5    5       4
TOA A       12    8       5

5.3 - Thực hành chuyển đổi giữa dạng rộng và dạng dài bằng stack() và unstack().

In [4]:
# Dạng RỘNG --> DÀI
stacked = pivot_repair_time.stack().reset_index()
stacked.columns = ["facility_type", "building", "avg_duration_hours"]

stacked

# Dạng DÀI --> RỘNG
unstacked = stacked.set_index(
    ["facility_type", "building"]
)["avg_duration_hours"].unstack()

unstacked

building          A   A-BLOCK       B   BLOCK C         C   TOA A
facility_type
Hoi Truong     3.00       NaN  1.5000  3.916667  5.000000  3.6875
Lab             NaN  3.089286  3.1875       NaN       NaN  3.1250
Phong  Hoc     2.00  2.000000     NaN  2.125000       NaN     NaN
Phong Hoc       NaN  2.875000  2.3500       NaN  4.250000  3.8500
Studio         4.25  3.250000  3.5000  2.875000  2.416667     NaN

5.4. Phân tích kết quả Pivot

1. Thời gian sửa chữa trung bình theo facility_type × building
- Từ bảng pivot cho thấy, **facility_type = …** tại **building = …** có
  thời gian sửa chữa trung bình cao nhất.
- Điều này cho thấy các cơ sở thuộc loại này tại building trên có mức độ
  hư hỏng phức tạp hoặc quy trình bảo trì chưa hiệu quả.

2. Số lượng sự cố theo building × severity
- Một số building như **…** có số lượng sự cố mức **severity = High**
  cao hơn các khu vực khác.
- Điều này phản ánh mức độ rủi ro vận hành và nhu cầu kiểm tra định kỳ
  cao tại các building này.

3. Đánh giá loại cơ sở cần ưu tiên bảo trì
- Kết hợp hai bảng pivot, có thể nhận thấy **facility_type = …** vừa có
  **thời gian sửa chữa trung bình cao**, vừa xuất hiện nhiều sự cố nghiêm trọng.
- Do đó, đây là loại cơ sở **cần được ưu tiên bảo trì và nâng cấp** trong
  kế hoạch quản lý CSVC.

4. Nhận xét tổng quát
- Phân tích pivot giúp phát hiện các điểm nóng về bảo trì theo nhiều chiều:
  loại cơ sở – tòa nhà – mức độ sự cố.
- Kết quả là cơ sở quan trọng cho việc ra quyết định phân bổ nguồn lực bảo trì.

In [5]:
pivot_repair_time.to_csv("../final_report/pivot_avg_repair_time.csv")
pivot_incident_count.to_csv("../final_report/pivot_incident_severity.csv")